Tree: fcarouge::tree< Type, AllocatorType > Class Template Reference
fcarouge::tree< Type, AllocatorType > Class Template Reference
A tree data structure for C++.
#include <tree.hpp>
Classes
struct const_iterator
Type to identify and traverse the constant elements of the container.
struct insert_return_type
The result type of inserting a node_type in the container.
struct internal_node_type
Branch node data structure type.
struct iterator
Type to identify and traverse the elements of the container.
class node_type
The node handle type of the container.
Public Types
Public Member Types
using value_type = Type
The type of the contained data elements.
using allocator_type = AllocatorType
The type of the allocator for all memory allocations of this container.
using size_type = std::size_t
The unsigned integer type to represent element counts.
using difference_type = std::ptrdiff_t
Signed integer type to represent element distances.
using reference = value_type &
The reference type of the contained data elements.
using const_reference = const value_type &
The constant reference type of the contained data elements.
using pointer = typename std::allocator_traits< AllocatorType >::pointer
The pointer type of the contained data elements.
using const_pointer = typename std::allocator_traits< AllocatorType >::const_pointer
The constant pointer type of the contained data elements.
Public Member Functions
Public Member Functions
constexpr tree () noexcept(noexcept(AllocatorType{}))=default
Constructs an empty container with a default-constructed allocator.
constexpr tree (const AllocatorType &allocator) noexcept(noexcept(internal_node_allocator_type{ allocator }))
Constructs an empty container with the given allocator.
constexpr tree (const tree &other) noexcept
Copy constructs a container with a default-constructed allocator.
constexpr tree (const tree &other, const AllocatorType &allocator)
Copy constructs a container with an allocator.
constexpr tree (tree &&other) noexcept
Move constructs a container.
constexpr tree (tree &&other, const AllocatorType &allocator) noexcept
Allocator-extended move constructor.
constexpr tree (const_reference value)
Constructs the container with by copying the value for its root.
constexpr tree (const_reference value, const AllocatorType &allocator)
Constructs the container with by copying the value for its root.
constexpr tree (value_type &&value)
Constructs the container by moving the value for its root.
constexpr tree (value_type &&value, const AllocatorType &allocator)
Constructs the container by moving the value for its root.
constexpr ~tree () noexcept
Destructs the container.
tree & operator= (const tree &other)
Copy assignment operator.
constexpr tree & operator= (tree &&other) noexcept
Move assignment operator.
constexpr tree & operator= (const_reference value)
Value copy assignment operator.
constexpr tree & operator= (value_type &&value)
Value move assignment operator.
constexpr tree & assign (const tree &other) noexcept
Copy assignment.
constexpr tree & assign (tree &&other) noexcept
Move assignment.
constexpr tree & assign (const_reference value) noexcept
Value copy assignment.
constexpr tree & assign (value_type &&value) noexcept
Value move assignment.
constexpr allocator_type get_allocator () const noexcept
Returns the allocator associated with the container.
Public Element Access Member Functions
constexpr reference front ()
Returns a reference to the first element in the container.
constexpr const_reference front () const
Returns a constant reference to the first element in the container.
Public Iterator Member Functions
constexpr iterator begin () noexcept
Returns an iterator to the first element of the container.
constexpr const_iterator begin () const noexcept
Returns a constant iterator to the first element of the container.
constexpr const_iterator cbegin () const noexcept
Returns a constant iterator to the first element of the container.
constexpr iterator end () noexcept
Returns an iterator to the element following the last element of the container.
constexpr const_iterator end () const noexcept
Returns a constant iterator to the element following the last element of the container.
constexpr const_iterator cend () const noexcept
Returns a constant iterator to the element following the last element of the container.
Public Capacity Member Functions
constexpr bool empty () const noexcept
Checks if the container has no elements.
constexpr size_type size () const noexcept
Returns the number of elements in the container.
constexpr size_type max_size () const noexcept
Returns the maximum number of elements the container is able to hold.
Public Modifier Member Functions
constexpr void clear () noexcept
Erases all elements from the container.
constexpr iterator insert (const_iterator position, const_reference value)
Inserts a new element into the container copied directly before the position iterator as the new left sibling.
constexpr iterator insert (const_iterator position, value_type &&value)
Inserts a new element into the container moved directly before the position iterator as the new left sibling.
template<class InputIteratorType >
constexpr iterator insert (const_iterator position, InputIteratorType first, InputIteratorType last)
constexpr iterator insert (const_iterator position, std::initializer_list< Type > initializers)
template<class... ArgumentsType>
constexpr reference emplace_front (ArgumentsType &&... arguments)
Inserts a new element into the container constructed in-place to the beginning of the container.
template<class... ArgumentsType>
constexpr iterator emplace (const_iterator position, ArgumentsType &&... arguments)
Inserts a new element into the container constructed in-place directly before the position iterator as the new left sibling.
constexpr iterator erase (iterator position)
Removes the specified element including its sub-tree.
constexpr iterator erase (const_iterator position)
Removes the specified element including its sub-tree.
constexpr iterator push (const_iterator position, const_reference value)
Inserts the given element value into the container directly after the last child of the position iterator as the new last child.
constexpr iterator push (const_iterator position, value_type &&value)
Inserts the given element value into the container directly after the last child of the position iterator as the new last child.
constexpr void push_front (const_reference value)
Prepends the given element to the beginning of the container.
constexpr void push_front (value_type &&value)
Prepends the given element to the beginning of the container.
void swap (tree &other)
Exchanges the contents of this container with those of the other container.
Private Types
Private Member Types
using internal_node_allocator_type = typename std::allocator_traits< AllocatorType >::template rebind_alloc< internal_node_type >
Rebind the element type allocator to the internal container nodes allocator.
using internal_node_allocator_traits = std::allocator_traits< internal_node_allocator_type >
The node allocator traits access.
Private Member Functions
Private Modifier Member Functions
constexpr void cleave (internal_node_type *node)
Isolates the specified element including its sub-tree.
constexpr void prune (internal_node_type *node)
Recursively erases the specified element including its sub-tree.
constexpr void axe (internal_node_type *node)
Axes the specified element including its sub-tree.
template<class... ArgumentsType>
constexpr internal_node_type * emplace_last_child (internal_node_type *parent, ArgumentsType &&... arguments)
Inserts the given element value into the container directly after the last child of the position iterator as the new last child.
template<class... ArgumentsType>
constexpr void emplace_root (ArgumentsType &&... arguments)
Prepends the given element to the beginning of the container.
internal_node_type * copy (internal_node_type *other_node)
Copies the node, its subtrees, and right siblings recursively.
Private Attributes
Private Member Variables
internal_node_allocator_type node_allocator {}
internal_node_type * root = nullptr
The root node of the container.
size_type node_count = 0
The number of elements in the container.
Detailed Description
template<class Type, class AllocatorType = std::allocator<Type>>
class fcarouge::tree< Type, AllocatorType >
A tree data structure for C++.
The fcarouge::tree type is a hierarchical tree data structure. The container is:
generic with respect to the type of stored values and allocator as template parameters,
non-linear compared to arrays, linked lists, stacks, and queues as a node may lead to multiple nodes,
non-associative compared to maps and sets as values are not keyed,
unordered since internally, the elements are not sorted or maintained in any particular order but externally, the insertion order is upheld,
recursive in its facade exposing a recursively referenced collection of nodes, each containing a value,
standard layout class type which may help with memory and cross language communication,
unspecified iteration order except that each element is visited only once,
implemented operations without recursive calls to guarantee a constant stack usage limit,
compile time evaluation compatible,
employing generational C++ features advantageously up to C++20 standard,
separating algorithmic from container concerns,
influenced by the Standard Template Library (STL) principles and the C++ Core Guidelines in its design tradeoffs,
intelligibly documented for the wider audience.
Template Parameters
Type The type of the contained data elements. The requirements that are imposed on the elements depend on the actual operations performed on the container. Generally, it is required that element type meets the requirements of Erasable, but member functions impose stricter requirements. This container (but not its members) can be instantiated with an incomplete element type if the allocator satisfies the allocator completeness requirements.
AllocatorType An allocator that is used to acquire/release memory and to construct/destroy the elements in that memory. The type must meet the requirements of Allocator. The behavior is undefined if Allocator::value_type is not the same as Type.
Definition at line 108 of file tree.hpp.
Member Typedef Documentation
allocator_type
template<class Type , class AllocatorType = std::allocator<Type>> using fcarouge::tree< Type, AllocatorType >::allocator_type = AllocatorType
The type of the allocator for all memory allocations of this container.
Definition at line 124 of file tree.hpp.
const_pointer
template<class Type , class AllocatorType = std::allocator<Type>> using fcarouge::tree< Type, AllocatorType >::const_pointer = typename std::allocator_traits<AllocatorType>::const_pointer
The constant pointer type of the contained data elements.
Definition at line 142 of file tree.hpp.
const_reference
template<class Type , class AllocatorType = std::allocator<Type>> using fcarouge::tree< Type, AllocatorType >::const_reference = const value_type &
The constant reference type of the contained data elements.
Definition at line 136 of file tree.hpp.
difference_type
template<class Type , class AllocatorType = std::allocator<Type>> using fcarouge::tree< Type, AllocatorType >::difference_type = std::ptrdiff_t
Signed integer type to represent element distances.
Definition at line 130 of file tree.hpp.
internal_node_allocator_traits
template<class Type , class AllocatorType = std::allocator<Type>> using fcarouge::tree< Type, AllocatorType >::internal_node_allocator_traits = std::allocator_traits<internal_node_allocator_type> private
The node allocator traits access.
Definition at line 233 of file tree.hpp.
internal_node_allocator_type
template<class Type , class AllocatorType = std::allocator<Type>> using fcarouge::tree< Type, AllocatorType >::internal_node_allocator_type = typename std::allocator_traits< AllocatorType>::template rebind_alloc<internal_node_type> private
Rebind the element type allocator to the internal container nodes allocator.
Definition at line 229 of file tree.hpp.
pointer
template<class Type , class AllocatorType = std::allocator<Type>> using fcarouge::tree< Type, AllocatorType >::pointer = typename std::allocator_traits<AllocatorType>::pointer
The pointer type of the contained data elements.
Definition at line 139 of file tree.hpp.
reference
template<class Type , class AllocatorType = std::allocator<Type>> using fcarouge::tree< Type, AllocatorType >::reference = value_type &
The reference type of the contained data elements.
Definition at line 133 of file tree.hpp.
size_type
template<class Type , class AllocatorType = std::allocator<Type>> using fcarouge::tree< Type, AllocatorType >::size_type = std::size_t
The unsigned integer type to represent element counts.
Definition at line 127 of file tree.hpp.
value_type
template<class Type , class AllocatorType = std::allocator<Type>> using fcarouge::tree< Type, AllocatorType >::value_type = Type
The type of the contained data elements.
Definition at line 120 of file tree.hpp.
Constructor & Destructor Documentation
tree() [1/10]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr fcarouge::tree< Type, AllocatorType >::tree () constexpr default noexcept
Constructs an empty container with a default-constructed allocator.
Complexity
Constant.
Exceptions
Strong exception guarantees: no effect on exception. Same exceptions specification as the allocator AllocatorType default constructor, if any.
tree() [2/10]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr fcarouge::tree< Type, AllocatorType >::tree (const AllocatorType & allocator) inline explicit constexpr noexcept
Constructs an empty container with the given allocator.
Parameters
allocator Allocator to use for all memory allocations of this container.
Complexity
Constant.
Exceptions
Strong exception guarantees: no effect on exception. Same exceptions specification as the allocator AllocatorType copy constructor, if any.
Definition at line 483 of file tree.hpp.
                                            { allocator }))
           : node_allocator{ allocator }
   {
   }
tree() [3/10]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr fcarouge::tree< Type, AllocatorType >::tree (const tree< Type, AllocatorType > & other) inline constexpr noexcept
Copy constructs a container with a default-constructed allocator.
Constructs the container with the copy of the contents of the other container.
Parameters
other Another container to be used as source to initialize the elements of the container with.
Note
Allocator is obtained as if by calling: std::allocator_traits<AllocatorType>:: select_on_container_copy_construction(other.get_allocator())
Complexity
Linear in size of the other container.
Definition at line 502 of file tree.hpp.
           : node_allocator{ std::allocator_traits<AllocatorType>::
                                 select_on_container_copy_construction(
                                     other.node_allocator) },
             root{ copy(other.root) }, node_count{ other.node_count }
   {
   }
tree() [4/10]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr fcarouge::tree< Type, AllocatorType >::tree (const tree< Type, AllocatorType > & other, const AllocatorType & allocator) inline constexpr
Copy constructs a container with an allocator.
Allocator-extended copy constructor. Constructs the container with the copy of the contents of the other container.
Parameters
other Another container to be used as source to initialize the elements of the container with.
allocator Allocator to use for all memory allocations of this container.
Complexity
Linear in size of the other container.
Definition at line 521 of file tree.hpp.
           : node_allocator{ allocator }, root{ copy(other.root) }, node_count{
               other.node_count
             }
   {
   }
tree() [5/10]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr fcarouge::tree< Type, AllocatorType >::tree (tree< Type, AllocatorType > && other) inline constexpr noexcept
Move constructs a container.
Move constructor. Constructs the container with the contents of the other container using move semantics (i.e. the data in other container is moved from the other into this container). The allocator is obtained by move-construction from the allocator belonging to other.
Parameters
other Another container to be used as source to initialize the elements of the container with.
Complexity
Constant.
Definition at line 539 of file tree.hpp.
           : node_allocator{ std::move(other.node_allocator) },
             root{ other.root }, node_count{ other.node_count }
   {
     other.root = nullptr;
   }
tree() [6/10]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr fcarouge::tree< Type, AllocatorType >::tree (tree< Type, AllocatorType > && other, const AllocatorType & allocator) inline constexpr noexcept
Allocator-extended move constructor.
Constructs the container with the contents of the other using move semantics (i.e. the data in other container is moved from the other into this container). Using the provided allocator for the new container, moving the contents from other; if allocator != other.get_allocator(), this results in an element-wise move.
Parameters
other Another container to be used as source to initialize the elements of the container with.
allocator Allocator to use for all memory allocations of this container.
Complexity
Constant.
Definition at line 560 of file tree.hpp.
           : node_allocator{ allocator }, node_count{ other.node_count }
   {
     if (allocator != other.node_allocator) {
       root = copy(other.root);
     } else {
       root = other.root;
       other.root = nullptr;
     }
   }
tree() [7/10]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr fcarouge::tree< Type, AllocatorType >::tree (const_reference value) inline explicit constexpr
Constructs the container with by copying the value for its root.
Parameters
value The value to initialize elements of the container with.
Complexity
Constant.
Definition at line 576 of file tree.hpp.
           : root{ node_allocator.allocate(1) }, node_count{ 1 }
   {
     std::construct_at(root, value);
   }
References fcarouge::tree< Type, AllocatorType >::root.
tree() [8/10]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr fcarouge::tree< Type, AllocatorType >::tree (const_reference value, const AllocatorType & allocator) inline constexpr
Constructs the container with by copying the value for its root.
Parameters
value The value to initialize elements of the container with.
allocator Allocator to use for all memory allocations of this container.
Complexity
Constant.
Definition at line 589 of file tree.hpp.
           : node_allocator{ allocator }, root{ node_allocator.allocate(1) },
             node_count{ 1 }
   {
     std::construct_at(root, value);
   }
References fcarouge::tree< Type, AllocatorType >::root.
tree() [9/10]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr fcarouge::tree< Type, AllocatorType >::tree (value_type && value) inline explicit constexpr
Constructs the container by moving the value for its root.
Parameters
value The value to initialize elements of the container with.
Complexity
Constant.
Definition at line 601 of file tree.hpp.
           : root{ node_allocator.allocate(1) }, node_count{ 1 }
   {
     std::construct_at(root, std::move(value));
   }
References fcarouge::tree< Type, AllocatorType >::root.
tree() [10/10]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr fcarouge::tree< Type, AllocatorType >::tree (value_type && value, const AllocatorType & allocator) inline constexpr
Constructs the container by moving the value for its root.
Parameters
value The value to initialize elements of the container with.
allocator Allocator to use for all memory allocations of this container.
Complexity
Constant.
Definition at line 614 of file tree.hpp.
           : node_allocator{ allocator }, root{ node_allocator.allocate(1) },
             node_count{ 1 }
   {
     std::construct_at(root, std::move(value));
   }
References fcarouge::tree< Type, AllocatorType >::root.
~tree()
template<class Type , class AllocatorType = std::allocator<Type>> constexpr fcarouge::tree< Type, AllocatorType >::~tree () inline constexpr noexcept
Destructs the container.
The destructors of the elements are called and the used storage is deallocated.
Note
If the elements are pointers, the pointed-to objects are not destroyed.
Complexity
Linear in the size of the container.
Exceptions
The exception specification needs to be confirmed.
Definition at line 632 of file tree.hpp.
   {
     axe(root);
   }
References fcarouge::tree< Type, AllocatorType >::axe(), and fcarouge::tree< Type, AllocatorType >::root.
Member Function Documentation
assign() [1/4]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr tree& fcarouge::tree< Type, AllocatorType >::assign (const tree< Type, AllocatorType > & other) inline constexpr noexcept
Copy assignment.
Destroys or copy-assigns the contents with a copy of the contents of the other container. Self copy assignement is valid, safe, and meets specifications.
Parameters
other Another container to be used as source to initialize the elements of the container with.
Returns
The reference value of this implicit object container parameter, i.e. *this.
Complexity
Linear in the size of this and the other container.
Definition at line 747 of file tree.hpp.
   {
     if (this != std::addressof(other)) {
       axe(root);
       node_allocator = std::allocator_traits<AllocatorType>::
           select_on_container_copy_construction(other.node_allocator);
       root = copy(other.root);
       node_count = other.node_count;
     }
     return *this;
   }
References fcarouge::tree< Type, AllocatorType >::axe(), fcarouge::tree< Type, AllocatorType >::copy(), fcarouge::tree< Type, AllocatorType >::node_allocator, fcarouge::tree< Type, AllocatorType >::node_count, and fcarouge::tree< Type, AllocatorType >::root.
assign() [2/4]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr tree& fcarouge::tree< Type, AllocatorType >::assign (const_reference value) inline constexpr noexcept
Value copy assignment.
Replaces the contents of the container with a copy of the contents of the value for its root.
Parameters
value The value to initialize the container with.
Returns
The reference value of this implicit object container parameter, i.e. *this.
Complexity
Linear in the size of this container.
Definition at line 801 of file tree.hpp.
   {
     axe(root);
     root = node_allocator.allocate(1);
     std::construct_at(root, value);
     node_count = 1;
     return *this;
   }
References fcarouge::tree< Type, AllocatorType >::axe(), fcarouge::tree< Type, AllocatorType >::node_allocator, fcarouge::tree< Type, AllocatorType >::node_count, and fcarouge::tree< Type, AllocatorType >::root.
assign() [3/4]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr tree& fcarouge::tree< Type, AllocatorType >::assign (tree< Type, AllocatorType > && other) inline constexpr noexcept
Move assignment.
Replaces the contents of the container with those of the other container using move semantics (i.e. the data in other container is moved from the other into this container). The other container is in a valid but unspecified state afterwards. The allocator is obtained by move-construction from the allocator belonging to other. Self move assignement is valid, safe, and meets specifications.
Parameters
other Another container to be used as source to initialize the elements of the container with.
Returns
The reference value of this implicit object container parameter, i.e. *this.
Complexity
Constant.
Exceptions
Same exceptions specification as the allocator AllocatorType move assignment operator, if any.
Definition at line 778 of file tree.hpp.
   {
     if (this != std::addressof(other)) {
       axe(root);
       node_allocator = std::move(other.node_allocator);
       root = other.root;
       node_count = other.node_count;
       other.root = nullptr;
     }
     return *this;
   }
References fcarouge::tree< Type, AllocatorType >::axe(), fcarouge::tree< Type, AllocatorType >::node_allocator, fcarouge::tree< Type, AllocatorType >::node_count, and fcarouge::tree< Type, AllocatorType >::root.
assign() [4/4]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr tree& fcarouge::tree< Type, AllocatorType >::assign (value_type && value) inline constexpr noexcept
Value move assignment.
Replaces the contents of the container with those of the value using move semantics (i.e. the value data is moved into the root of this container). The value is in a valid but unspecified state afterwards.
Parameters
value The value to initialize the container with.
Returns
The reference value of this implicit object container parameter, i.e. *this.
Complexity
Linear in the size of this container.
Definition at line 822 of file tree.hpp.
   {
     axe(root);
     root = node_allocator.allocate(1);
     std::construct_at(root, std::move(value));
     node_count = 1;
     return *this;
   }
References fcarouge::tree< Type, AllocatorType >::axe(), fcarouge::tree< Type, AllocatorType >::node_allocator, fcarouge::tree< Type, AllocatorType >::node_count, and fcarouge::tree< Type, AllocatorType >::root.
axe()
template<class Type , class AllocatorType = std::allocator<Type>> constexpr void fcarouge::tree< Type, AllocatorType >::axe (internal_node_type * node) inline constexpr private
Axes the specified element including its sub-tree.
Removes the node element and removes its associated sub-tree. References and iterators to the erased elements are invalidated. Other references and iterators are not affected. The container's size is not maintained and no longer corresponds to the container content.
Parameters
node The pointer to the element to erase.
Definition at line 1586 of file tree.hpp.
   {
     while (internal_node_type *current = node) {
       if (current->last_child) {
         if (current->right_sibling) {
           current->last_child->right_sibling = current->right_sibling;
         }
         node = current->first_child;
       } else if (current->right_sibling) {
         node = current->right_sibling;
       } else {
         node = nullptr;
       }
       std::destroy_at(current);
       node_allocator.deallocate(current, 1);
     }
   }
References fcarouge::tree< Type, AllocatorType >::internal_node_type::first_child, fcarouge::tree< Type, AllocatorType >::node_allocator, and fcarouge::tree< Type, AllocatorType >::internal_node_type::right_sibling.
Referenced by fcarouge::tree< Type, AllocatorType >::assign(), fcarouge::tree< Type, AllocatorType >::clear(), fcarouge::tree< Type, AllocatorType >::operator=(), and fcarouge::tree< Type, AllocatorType >::~tree().
begin() [1/2]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr const_iterator fcarouge::tree< Type, AllocatorType >::begin () const inline constexpr noexcept
Returns a constant iterator to the first element of the container.
If the container is empty, the returned constant iterator will be equal to end().
Returns
Constant iterator to the first element.
Complexity
Constant.
Definition at line 903 of file tree.hpp.
   {
     return { root };
   }
References fcarouge::tree< Type, AllocatorType >::root.
begin() [2/2]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr iterator fcarouge::tree< Type, AllocatorType >::begin () inline constexpr noexcept
Returns an iterator to the first element of the container.
If the container is empty, the returned iterator will be equal to end().
Returns
Iterator to the first element.
Complexity
Constant.
Definition at line 890 of file tree.hpp.
   {
     return { root };
   }
References fcarouge::tree< Type, AllocatorType >::root.
cbegin()
template<class Type , class AllocatorType = std::allocator<Type>> constexpr const_iterator fcarouge::tree< Type, AllocatorType >::cbegin () const inline constexpr noexcept
Returns a constant iterator to the first element of the container.
If the container is empty, the returned constant iterator will be equal to end().
Returns
Constant iterator to the first element.
Complexity
Constant.
Definition at line 916 of file tree.hpp.
   {
     return { root };
   }
References fcarouge::tree< Type, AllocatorType >::root.
cend()
template<class Type , class AllocatorType = std::allocator<Type>> constexpr const_iterator fcarouge::tree< Type, AllocatorType >::cend () const inline constexpr noexcept
Returns a constant iterator to the element following the last element of the container.
This element acts as a placeholder; attempting to access it results in undefined behavior. If the container is empty, the returned constant iterator will be equal to begin().
Returns
Constant iterator to the element following the last element.
Complexity
Constant.
Definition at line 961 of file tree.hpp.
   {
     return { nullptr };
   }
clear()
template<class Type , class AllocatorType = std::allocator<Type>> constexpr void fcarouge::tree< Type, AllocatorType >::clear () inline constexpr noexcept
Erases all elements from the container.
After this call, the size member function calls returns zero. Invalidates any references, pointers, or iterators referring to contained elements. Any past-the-end iterator remains valid.
Complexity
Linear in size of this container, i.e., the number of elements.
Benchmark
Definition at line 1039 of file tree.hpp.
   {
     axe(root);
     root = nullptr;
     node_count = 0;
   }
References fcarouge::tree< Type, AllocatorType >::axe(), fcarouge::tree< Type, AllocatorType >::node_count, and fcarouge::tree< Type, AllocatorType >::root.
cleave()
template<class Type , class AllocatorType = std::allocator<Type>> constexpr void fcarouge::tree< Type, AllocatorType >::cleave (internal_node_type * node) inline constexpr private
Isolates the specified element including its sub-tree.
Orphans the node from its parent and disolves its sibling relationships. The container's size is not maintained and no longer corresponds to the container content. Cleaving the root or last node has the expected effects on the tree.
Parameters
node The pointer to the element to cleave.
Definition at line 1525 of file tree.hpp.
   {
     if (node == root) {
       root = nullptr;
     }
     if (node->parent) {
       if (node->parent->first_child == node) {
         node->parent->first_child = node->right_sibling;
       }
       if (node->parent->last_child == node) {
         node->parent->last_child = node->left_sibling;
       }
     }
     if (node->left_sibling) {
       node->left_sibling->right_sibling = node->right_sibling;
       node->left_sibling = nullptr;
     }
     if (node->right_sibling) {
       node->right_sibling->left_sibling = node->left_sibling;
       node->right_sibling = nullptr;
     }
   }
References fcarouge::tree< Type, AllocatorType >::internal_node_type::first_child, fcarouge::tree< Type, AllocatorType >::internal_node_type::last_child, fcarouge::tree< Type, AllocatorType >::internal_node_type::left_sibling, fcarouge::tree< Type, AllocatorType >::internal_node_type::parent, fcarouge::tree< Type, AllocatorType >::internal_node_type::right_sibling, and fcarouge::tree< Type, AllocatorType >::root.
Referenced by fcarouge::tree< Type, AllocatorType >::erase().
copy()
template<class Type , class AllocatorType = std::allocator<Type>> internal_node_type* fcarouge::tree< Type, AllocatorType >::copy (internal_node_type * other_node) inline private
Copies the node, its subtrees, and right siblings recursively.
Constructs a new node from the other_node element value. Attaches the newly created child to its parent, if any. Attaches the newly created right sibling to its left sibling, if any.
Parameters
other_node The other tree node to copy.
Complexity
Linear in the size of the number of nodes copied.
Definition at line 1729 of file tree.hpp.
   {
     // If there is another node to copy...
     if (other_node) {
       // ...allocate and in-place construct the first node with this container's
       // allocator and the other node data value...
       internal_node_type *first = node_allocator.allocate(1);
       std::construct_at(first, other_node->data, nullptr, nullptr, nullptr,
                         nullptr, nullptr);
       // ...walk the other tree to copy and track the tree copied...
       internal_node_type *next_other = other_node->first_child;
       internal_node_type *next_parent = first;
       internal_node_type *next_left_sibling = nullptr;
       // ...for every node to copy...
       while (next_other) {
         // ...allocate and in-place construct a node with this container's
         // allocator, the other node data value, and any left sibling or parent
         // pointers...
         internal_node_type *node = node_allocator.allocate(1);
         std::construct_at(node, next_other->data, nullptr, nullptr,
                           next_left_sibling, nullptr, next_parent);
         // ...reference any parent and left sibling to the new node...
         next_parent->last_child = node;
         if (next_left_sibling) {
           next_left_sibling->right_sibling = node;
         } else {
           next_parent->first_child = node;
         }
         // ...walk to the next other tree node to copy and walk and track the
         // copied tree alongside...
         next_parent = node;
         next_left_sibling = nullptr;
         if (next_other->first_child) {
           next_other = next_other->first_child;
         } else {
           // ...going back to the next ancestor sibling and tracking as
           // necessary.
           while (next_other) {
             if (next_other->right_sibling) {
               next_other = next_other->right_sibling;
               break;
             }
             next_other = next_other->parent;
             next_parent = next_parent->parent;
             next_left_sibling = next_parent->last_child;
           }
         }
       };
       return first;
     }
     return nullptr;
   }
References fcarouge::tree< Type, AllocatorType >::internal_node_type::data, fcarouge::tree< Type, AllocatorType >::internal_node_type::first_child, fcarouge::tree< Type, AllocatorType >::internal_node_type::last_child, fcarouge::tree< Type, AllocatorType >::node_allocator, fcarouge::tree< Type, AllocatorType >::internal_node_type::parent, and fcarouge::tree< Type, AllocatorType >::internal_node_type::right_sibling.
Referenced by fcarouge::tree< Type, AllocatorType >::assign(), and fcarouge::tree< Type, AllocatorType >::operator=().
emplace()
template<class Type , class AllocatorType = std::allocator<Type>> template<class... ArgumentsType> constexpr iterator fcarouge::tree< Type, AllocatorType >::emplace (const_iterator position, ArgumentsType &&... arguments) inline constexpr
Inserts a new element into the container constructed in-place directly before the position iterator as the new left sibling.
The element is constructed through std::construct_at equivalenent to placement-new to construct the element in-place, usable in evaluation of constant expressions, at a location provided by the container. The arguments are forwarded to the constructor as std::forward<ArgumentsType>(arguments).... No iterators or references are invalidated. Inserts at the root position as the new root. Inserts before the beginning begin() position as the new root. Inserts before the ending end() position.
Template Parameters
ArgumentsType The argument types to forward to the constructor of the element.
Parameters
position The constant iterator before which the new element will be constructed. The iterator may be the beginning begin() or ending end() iterator.
arguments The arguments to forward to the constructor of the element.
Returns
The iterator pointing to the inserted element.
Complexity
Constant.
Definition at line 1265 of file tree.hpp.
   {
     // The allocated node is in-place construced and recorded in every
     // following statements.
     internal_node_type *node = node_allocator.allocate(1);
     // Insert the new node before the position node...
     if (internal_node_type *position_node = position.node) {
       // ...as the new left child...
       if (position_node->parent) {
         std::construct_at(node, std::forward<ArgumentsType>(arguments)...,
                           nullptr, nullptr, position_node->left_sibling,
                           position_node, position_node->parent);
         position_node->left_sibling = node;
         // ...with a left sibling node.
         if (internal_node_type *left_node = node->left_sibling) {
           left_node->right_sibling = node;
         }
         // ...without a left sibling node.
         else {
           position_node->parent->first_child = node;
         }
       }
       // ...as the new root.
       else {
         std::construct_at(node, std::forward<ArgumentsType>(arguments)...,
                           position_node, position_node);
         position_node->parent = node;
         root = node;
       }
     }
     // ...as the new last node...
     else {
       // ... as the last child of the root node.
       if (root) {
         std::construct_at(node, std::forward<ArgumentsType>(arguments)...,
                           nullptr, nullptr, root->last_child, nullptr, root);
         if (!root->first_child) {
           root->first_child = node;
         }
         if (root->last_child) {
           root->last_child->right_sibling = node;
         }
         root->last_child = node;
       }
       // ...as the sole, and root node.
       else {
         std::construct_at(node, std::forward<ArgumentsType>(arguments)...);
         root = node;
       }
     }
     ++node_count;
     return { node };
   }
References fcarouge::tree< Type, AllocatorType >::internal_node_type::first_child, fcarouge::tree< Type, AllocatorType >::internal_node_type::last_child, fcarouge::tree< Type, AllocatorType >::internal_node_type::left_sibling, fcarouge::tree< Type, AllocatorType >::const_iterator::node, fcarouge::tree< Type, AllocatorType >::node_allocator, fcarouge::tree< Type, AllocatorType >::node_count, fcarouge::tree< Type, AllocatorType >::internal_node_type::parent, fcarouge::tree< Type, AllocatorType >::internal_node_type::right_sibling, and fcarouge::tree< Type, AllocatorType >::root.
emplace_front()
template<class Type , class AllocatorType = std::allocator<Type>> template<class... ArgumentsType> constexpr reference fcarouge::tree< Type, AllocatorType >::emplace_front (ArgumentsType &&... arguments) inline constexpr
Inserts a new element into the container constructed in-place to the beginning of the container.
The element is constructed through std::construct_at equivalenent to placement-new to construct the element in-place, usable in evaluation of constant expressions, at a location provided by the container. The arguments are forwarded to the constructor as std::forward<ArgumentsType>(arguments).... No iterators or references are invalidated. Inserts at the root position as the new root.
Template Parameters
ArgumentsType The argument types to forward to the constructor of the element.
Parameters
arguments The arguments to forward to the constructor of the element.
Returns
Reference to the inserted element.
Complexity
Constant.
Benchmark
Definition at line 1221 of file tree.hpp.
   {
     // The allocated node is in-place construced and recorded in every
     // following statements.
     internal_node_type *node = node_allocator.allocate(1);
     // Insert the new node...
     std::construct_at(node, std::forward<ArgumentsType>(arguments)..., root,
                       root, nullptr, nullptr, nullptr);
     // ...as the new root node.
     if (root) {
       root->parent = node;
     }
     root = node;
     ++node_count;
     return node->data;
   }
References fcarouge::tree< Type, AllocatorType >::internal_node_type::data, fcarouge::tree< Type, AllocatorType >::node_allocator, fcarouge::tree< Type, AllocatorType >::node_count, fcarouge::tree< Type, AllocatorType >::internal_node_type::parent, and fcarouge::tree< Type, AllocatorType >::root.
emplace_last_child()
template<class Type , class AllocatorType = std::allocator<Type>> template<class... ArgumentsType> constexpr internal_node_type* fcarouge::tree< Type, AllocatorType >::emplace_last_child (internal_node_type * parent, ArgumentsType &&... arguments) inline constexpr private
Inserts the given element value into the container directly after the last child of the position iterator as the new last child.
No iterators or references are invalidated. The new element is in-place constructed and moved, or copied. Inserts after the beginning begin() position as the last child of the root if present, or as the root if the container is empty. Inserts after the ending end() position as the sole child of the last node if present, or as the root if the container is empty.
Template Parameters
ArgumentsType The argument types to forward to the constructor of the element.
Parameters
parent The parent node for which the element will be inserted as the last child. Emplacing a node without a parent places the node at the end.
arguments The construction data of the element to insert.
Returns
The iterator pointing to the inserted element.
Exceptions
Strong exception guarantees: no effect on exception. The Allocator::allocate() allocation or the element copy/move constructor/assignment may throw. If Type's move constructor is not noexcept and Type is not CopyInsertable into *this, the container will use the throwing move constructor. If it throws, the guarantee is waived and the effects are unspecified.
Definition at line 1634 of file tree.hpp.
   {
     // The allocated child node is in-place construced and recorded in every
     // following statements.
     internal_node_type *child = node_allocator.allocate(1);
     // Insert the new node...
     // ...as the last child of the position node...
     if (parent) {
       std::construct_at(child, std::forward<ArgumentsType>(arguments)...,
                         nullptr, nullptr, parent->last_child, nullptr, parent);
       parent->last_child = child;
       // ...with a left sibling node.
       if (child->left_sibling) {
         child->left_sibling->right_sibling = child;
       }
       // ...without a left sibling node.
       else {
         parent->first_child = child;
         // ...whose parent was the last node...
       }
     }
     // ...as the new last node...
     else {
       // ... as the last child of the root node.
       if (root) {
         std::construct_at(child, std::forward<ArgumentsType>(arguments)...,
                           nullptr, nullptr, root->last_child, nullptr, root);
         if (!root->first_child) {
           root->first_child = child;
         }
         if (root->last_child) {
           root->last_child->right_sibling = child;
         }
         root->last_child = child;
       }
       // ...as the sole, and root node.
       else {
         std::construct_at(child, std::forward<ArgumentsType>(arguments)...);
         root = child;
       }
     }
     ++node_count;
     return child;
   }
References fcarouge::tree< Type, AllocatorType >::internal_node_type::first_child, fcarouge::tree< Type, AllocatorType >::internal_node_type::last_child, fcarouge::tree< Type, AllocatorType >::internal_node_type::left_sibling, fcarouge::tree< Type, AllocatorType >::node_allocator, fcarouge::tree< Type, AllocatorType >::node_count, fcarouge::tree< Type, AllocatorType >::internal_node_type::right_sibling, and fcarouge::tree< Type, AllocatorType >::root.
Referenced by fcarouge::tree< Type, AllocatorType >::push().
emplace_root()
template<class Type , class AllocatorType = std::allocator<Type>> template<class... ArgumentsType> constexpr void fcarouge::tree< Type, AllocatorType >::emplace_root (ArgumentsType &&... arguments) inline constexpr private
Prepends the given element to the beginning of the container.
Prepends the given element as the new root. If the container is not empty the root becomes the sole child of the prepended element. No iterators or references are invalidated. The new element is in-place constructed and moved, or copied.
Template Parameters
ArgumentsType The argument types to forward to the constructor of the element.
Parameters
arguments The construction data of the element to insert.
Complexity
Constant.
Exceptions
Strong exception guarantees: no effect on exception. The Allocator::allocate() allocation or the element copy/move constructor/assignment may throw.
Definition at line 1701 of file tree.hpp.
   {
     // The allocated node is in-place construced and recorded in every
     // following statements.
     internal_node_type *node = node_allocator.allocate(1);
     // Insert the new node and prepare it to be the new root...
     std::construct_at(node, std::forward<ArgumentsType>(arguments)..., root,
                       root);
     // ... by displacing the previous root.
     if (root) {
       root->parent = node;
     }
     root = node;
     ++node_count;
   }
References fcarouge::tree< Type, AllocatorType >::node_allocator, fcarouge::tree< Type, AllocatorType >::node_count, fcarouge::tree< Type, AllocatorType >::internal_node_type::parent, and fcarouge::tree< Type, AllocatorType >::root.
Referenced by fcarouge::tree< Type, AllocatorType >::push_front().
empty()
template<class Type , class AllocatorType = std::allocator<Type>> constexpr bool fcarouge::tree< Type, AllocatorType >::empty () const inline constexpr noexcept
Checks if the container has no elements.
Whether the beginning iterator equals the ending iterator.
Returns
true if the container is empty, false otherwise.
Complexity
Constant.
Definition at line 978 of file tree.hpp.
   {
     return node_count == 0;
   }
References fcarouge::tree< Type, AllocatorType >::node_count.
end() [1/2]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr const_iterator fcarouge::tree< Type, AllocatorType >::end () const inline constexpr noexcept
Returns a constant iterator to the element following the last element of the container.
This element acts as a placeholder; attempting to access it results in undefined behavior. If the container is empty, the returned constant iterator will be equal to begin().
Returns
Constant iterator to the element following the last element.
Complexity
Constant.
Definition at line 946 of file tree.hpp.
   {
     return { nullptr };
   }
end() [2/2]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr iterator fcarouge::tree< Type, AllocatorType >::end () inline constexpr noexcept
Returns an iterator to the element following the last element of the container.
This element acts as a placeholder; attempting to access it results in undefined behavior. If the container is empty, the returned constant iterator will be equal to begin().
Returns
Iterator to the element following the last element.
Complexity
Constant.
Definition at line 931 of file tree.hpp.
   {
     return { nullptr };
   }
erase() [1/2]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr iterator fcarouge::tree< Type, AllocatorType >::erase (const_iterator position) inline constexpr
Removes the specified element including its sub-tree.
Removes the element at position and its associated sub-tree. References and iterators to the erased elements are invalidated. Other references and iterators are not affected. The iterator position must be valid and dereferenceable. Thus the end() iterator which is valid, but is not dereferenceable cannot be used as a value for position. The same is applicable for the begin() iterator on an empty container. The container's size is reduded by the number of elements removed, that is the node and all nodes in its sub-tree. If the erased node is the root, the tree is empty.
Parameters
position The constant iterator to the element to remove with its subtree.
Returns
Iterator following the last removed element. If position refers to the last element, then the end() iterator is returned.
Definition at line 1366 of file tree.hpp.
   {
     // Identify the node following this subtree which will become the next node,
     // separate the subtree out of the tree, and recursively erase the subtree.
     internal_node_type *next{ position.node->next_ancestor_sibling() };
     cleave(position.node);
     prune(position.node);
     return { next };
   }
References fcarouge::tree< Type, AllocatorType >::cleave(), fcarouge::tree< Type, AllocatorType >::internal_node_type::next_ancestor_sibling(), fcarouge::tree< Type, AllocatorType >::const_iterator::node, and fcarouge::tree< Type, AllocatorType >::prune().
erase() [2/2]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr iterator fcarouge::tree< Type, AllocatorType >::erase (iterator position) inline constexpr
Removes the specified element including its sub-tree.
Removes the element at position and its associated sub-tree. References and iterators to the erased elements are invalidated. Other references and iterators are not affected. The iterator position must be valid and dereferenceable. Thus the end() iterator which is valid, but is not dereferenceable cannot be used as a value for position. The same is applicable for the begin() iterator on an empty container. The container's size is reduded by the number of elements removed, that is the node and all nodes in its sub-tree. If the erased node is the root, the tree is empty.
Parameters
position The iterator to the element to remove with its subtree.
Returns
Iterator following the last removed element. If position refers to the last element, then the end() iterator is returned.
Definition at line 1338 of file tree.hpp.
   {
     // Identify the node following this subtree which will become the next node,
     // separate the subtree out of the tree, and recursively erase the subtree.
     internal_node_type *next{ position.node->next_ancestor_sibling() };
     cleave(position.node);
     prune(position.node);
     return { next };
   }
References fcarouge::tree< Type, AllocatorType >::cleave(), fcarouge::tree< Type, AllocatorType >::internal_node_type::next_ancestor_sibling(), fcarouge::tree< Type, AllocatorType >::iterator::node, and fcarouge::tree< Type, AllocatorType >::prune().
front() [1/2]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr reference fcarouge::tree< Type, AllocatorType >::front () inline constexpr
Returns a reference to the first element in the container.
Calling front on an empty container causes undefined behavior.
Returns
Reference to the first element.
Complexity
Constant.
Note
For a non-empty container c, the expression c.front() is equivalent to *c.begin().
Definition at line 856 of file tree.hpp.
   {
     return root->data;
   }
References fcarouge::tree< Type, AllocatorType >::internal_node_type::data, and fcarouge::tree< Type, AllocatorType >::root.
front() [2/2]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr const_reference fcarouge::tree< Type, AllocatorType >::front () const inline constexpr
Returns a constant reference to the first element in the container.
Calling front on an empty container causes undefined behavior.
Returns
Constant reference to the first element.
Complexity
Constant.
Note
For a non-empty container c, the expression c.front() is equivalent to *c.begin().
Definition at line 872 of file tree.hpp.
   {
     return root->data;
   }
References fcarouge::tree< Type, AllocatorType >::internal_node_type::data, and fcarouge::tree< Type, AllocatorType >::root.
get_allocator()
template<class Type , class AllocatorType = std::allocator<Type>> constexpr allocator_type fcarouge::tree< Type, AllocatorType >::get_allocator () const inline constexpr noexcept
Returns the allocator associated with the container.
Returns
The associated allocator.
Complexity
Constant.
Definition at line 836 of file tree.hpp.
   {
     return node_allocator;
   }
References fcarouge::tree< Type, AllocatorType >::node_allocator.
insert() [1/4]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr iterator fcarouge::tree< Type, AllocatorType >::insert (const_iterator position, const_reference value) inline constexpr
Inserts a new element into the container copied directly before the position iterator as the new left sibling.
The value is copied at a location element provided by the container. No iterators or references are invalidated. Inserts at the root position as the new root. Inserts before the beginning begin() position as the new root. Inserts before the ending end() position.
Parameters
position The constant iterator before which the new element will be constructed. The iterator may be the beginning begin() or ending end() iterator.
value The value to copy in the the element node.
Returns
The iterator pointing to the inserted element.
Complexity
Constant.
Definition at line 1062 of file tree.hpp.
   {
     // The allocated node is in-place construced and recorded in every
     // following statements.
     internal_node_type *node = node_allocator.allocate(1);
     // Insert the new node...
     // ...before the position node...
     if (internal_node_type *position_node = position.node) {
       // ...as the new left child...
       if (position_node->parent) {
         std::construct_at(node, value, nullptr, nullptr,
                           position_node->left_sibling, position_node,
                           position_node->parent);
         position_node->left_sibling = node;
         // ...with a left sibling node.
         if (internal_node_type *left_node = node->left_sibling) {
           left_node->right_sibling = node;
         }
         // ...without a left sibling node.
         else {
           position_node->parent->first_child = node;
         }
       }
       // ...as the new root.
       else {
         std::construct_at(node, value, position_node, position_node);
         position_node->parent = node;
         root = node;
       }
     }
     // ...as the new last node...
     else {
       // ... as the last child of the root node.
       if (root) {
         std::construct_at(node, value, nullptr, nullptr, root->last_child,
                           nullptr, root);
         if (!root->first_child) {
           root->first_child = node;
         }
         if (root->last_child) {
           root->last_child->right_sibling = node;
         }
         root->last_child = node;
       }
       // ...as the sole, and root node.
       else {
         std::construct_at(node, value);
         root = node;
       }
     }
     ++node_count;
     return { node };
   }
References fcarouge::tree< Type, AllocatorType >::internal_node_type::first_child, fcarouge::tree< Type, AllocatorType >::internal_node_type::last_child, fcarouge::tree< Type, AllocatorType >::internal_node_type::left_sibling, fcarouge::tree< Type, AllocatorType >::const_iterator::node, fcarouge::tree< Type, AllocatorType >::node_allocator, fcarouge::tree< Type, AllocatorType >::node_count, fcarouge::tree< Type, AllocatorType >::internal_node_type::parent, fcarouge::tree< Type, AllocatorType >::internal_node_type::right_sibling, and fcarouge::tree< Type, AllocatorType >::root.
insert() [2/4]
template<class Type , class AllocatorType = std::allocator<Type>> template<class InputIteratorType > constexpr iterator fcarouge::tree< Type, AllocatorType >::insert (const_iterator position, InputIteratorType first, InputIteratorType last) constexpr
insert() [3/4]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr iterator fcarouge::tree< Type, AllocatorType >::insert (const_iterator position, std::initializer_list< Type > initializers) constexpr
insert() [4/4]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr iterator fcarouge::tree< Type, AllocatorType >::insert (const_iterator position, value_type && value) inline constexpr
Inserts a new element into the container moved directly before the position iterator as the new left sibling.
The value is moved at a location element provided by the container. No iterators or references are invalidated. Inserts at the root position as the new root. Inserts before the beginning begin() position as the new root. Inserts before the ending end() position.
Parameters
position The constant iterator before which the new element will be constructed. The iterator may be the beginning begin() or ending end() iterator.
value The value to move in the the element node.
Returns
The iterator pointing to the inserted element.
Complexity
Constant.
Definition at line 1134 of file tree.hpp.
   {
     // The allocated node is in-place construced and recorded in every
     // following statements.
     internal_node_type *node = node_allocator.allocate(1);
     // Insert the new node...
     // ...before the position node...
     if (internal_node_type *position_node = position.node) {
       // ...as the new left child...
       if (position_node->parent) {
         std::construct_at(node, std::move(value), nullptr, nullptr,
                           position_node->left_sibling, position_node,
                           position_node->parent);
         position_node->left_sibling = node;
         // ...with a left sibling node.
         if (internal_node_type *left_node = node->left_sibling) {
           left_node->right_sibling = node;
         }
         // ...without a left sibling node.
         else {
           position_node->parent->first_child = node;
         }
       }
       // ...as the new root.
       else {
         std::construct_at(node, std::move(value), position_node, position_node);
         position_node->parent = node;
         root = node;
       }
     }
     // ...as the new last node...
     else {
       // ... as the last child of the root node.
       if (root) {
         std::construct_at(node, std::move(value), nullptr, nullptr,
                           root->last_child, nullptr, root);
         if (!root->first_child) {
           root->first_child = node;
         }
         if (root->last_child) {
           root->last_child->right_sibling = node;
         }
         root->last_child = node;
       }
       // ...as the sole, and root node.
       else {
         std::construct_at(node, std::move(value));
         root = node;
       }
     }
     ++node_count;
     return { node };
   }
References fcarouge::tree< Type, AllocatorType >::internal_node_type::first_child, fcarouge::tree< Type, AllocatorType >::internal_node_type::last_child, fcarouge::tree< Type, AllocatorType >::internal_node_type::left_sibling, fcarouge::tree< Type, AllocatorType >::const_iterator::node, fcarouge::tree< Type, AllocatorType >::node_allocator, fcarouge::tree< Type, AllocatorType >::node_count, fcarouge::tree< Type, AllocatorType >::internal_node_type::parent, fcarouge::tree< Type, AllocatorType >::internal_node_type::right_sibling, and fcarouge::tree< Type, AllocatorType >::root.
max_size()
template<class Type , class AllocatorType = std::allocator<Type>> constexpr size_type fcarouge::tree< Type, AllocatorType >::max_size () const inline constexpr noexcept
Returns the maximum number of elements the container is able to hold.
The maximum number of elements depends on the system or library implementation limitations. The absolute distance between the beginning and end iterators for the largest container or the maximum number of element nodes theoretically allocated, whichever is smaller.
Returns
Maximum number of elements.
Complexity
Constant.
Note
This value typically reflects the theoretical limit on the size of the container, at most std:: numeric_limits<difference_type>:: max(), or at runtime, the size of the container may be limited to a value smaller than max_size() by the amount of memory (usualy RAM) available. The minima is selected without using and importing the minimum std::min operation from the <algorithm> library to reduce coupling.
Definition at line 1013 of file tree.hpp.
   {
     return internal_node_allocator_traits::max_size(node_allocator) <
                    static_cast<size_type>(
                        std::numeric_limits<difference_type>::max())
                ? internal_node_allocator_traits::max_size(node_allocator)
                : static_cast<size_type>(
                      std::numeric_limits<difference_type>::max());
   }
References fcarouge::tree< Type, AllocatorType >::node_allocator.
operator=() [1/4]
template<class Type , class AllocatorType = std::allocator<Type>> tree& fcarouge::tree< Type, AllocatorType >::operator= (const tree< Type, AllocatorType > & other) inline
Copy assignment operator.
Destroys or copy-assigns the contents with a copy of the contents of the other container. Self copy assignement is valid, safe, and meets specifications.
Parameters
other Another container to be used as source to initialize the elements of the container with.
Returns
The reference value of this implicit object container parameter, i.e. *this.
Complexity
Linear in the size of this and the other container.
Definition at line 650 of file tree.hpp.
   {
     if (this != std::addressof(other)) {
       axe(root);
       node_allocator = std::allocator_traits<AllocatorType>::
           select_on_container_copy_construction(other.node_allocator);
       root = copy(other.root);
       node_count = other.node_count;
     }
     return *this;
   }
References fcarouge::tree< Type, AllocatorType >::axe(), fcarouge::tree< Type, AllocatorType >::copy(), fcarouge::tree< Type, AllocatorType >::node_allocator, fcarouge::tree< Type, AllocatorType >::node_count, and fcarouge::tree< Type, AllocatorType >::root.
operator=() [2/4]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr tree& fcarouge::tree< Type, AllocatorType >::operator= (const_reference value) inline constexpr
Value copy assignment operator.
Replaces the contents of the container with a copy of the contents of the value for its root.
Parameters
value The value to initialize the container with.
Returns
The reference value of this implicit object container parameter, i.e. *this.
Complexity
Linear in the size of this container.
Definition at line 704 of file tree.hpp.
   {
     axe(root);
     root = node_allocator.allocate(1);
     std::construct_at(root, value);
     node_count = 1;
     return *this;
   }
References fcarouge::tree< Type, AllocatorType >::axe(), fcarouge::tree< Type, AllocatorType >::node_allocator, fcarouge::tree< Type, AllocatorType >::node_count, and fcarouge::tree< Type, AllocatorType >::root.
operator=() [3/4]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr tree& fcarouge::tree< Type, AllocatorType >::operator= (tree< Type, AllocatorType > && other) inline constexpr noexcept
Move assignment operator.
Replaces the contents of the container with those of the other container using move semantics (i.e. the data in other container is moved from the other into this container). The other container is in a valid but unspecified state afterwards. The allocator is obtained by move-construction from the allocator belonging to other. Self move assignement is valid, safe, and meets specifications.
Parameters
other Another container to be used as source to initialize the elements of the container with.
Returns
The reference value of this implicit object container parameter, i.e. *this.
Complexity
Constant.
Exceptions
Same exceptions specification as the allocator AllocatorType move assignment operator, if any.
Definition at line 681 of file tree.hpp.
   {
     if (this != std::addressof(other)) {
       axe(root);
       node_allocator = std::move(other.node_allocator);
       root = other.root;
       node_count = other.node_count;
       other.root = nullptr;
     }
     return *this;
   }
References fcarouge::tree< Type, AllocatorType >::axe(), fcarouge::tree< Type, AllocatorType >::node_allocator, fcarouge::tree< Type, AllocatorType >::node_count, and fcarouge::tree< Type, AllocatorType >::root.
operator=() [4/4]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr tree& fcarouge::tree< Type, AllocatorType >::operator= (value_type && value) inline constexpr
Value move assignment operator.
Replaces the contents of the container with those of the value using move semantics (i.e. the value data is moved into the root of this container). The value is in a valid but unspecified state afterwards.
Parameters
value The value to initialize the container with.
Returns
The reference value of this implicit object container parameter, i.e. *this.
Complexity
Linear in the size of this container.
Definition at line 725 of file tree.hpp.
   {
     axe(root);
     root = node_allocator.allocate(1);
     std::construct_at(root, std::move(value));
     node_count = 1;
     return *this;
   }
References fcarouge::tree< Type, AllocatorType >::axe(), fcarouge::tree< Type, AllocatorType >::node_allocator, fcarouge::tree< Type, AllocatorType >::node_count, and fcarouge::tree< Type, AllocatorType >::root.
prune()
template<class Type , class AllocatorType = std::allocator<Type>> constexpr void fcarouge::tree< Type, AllocatorType >::prune (internal_node_type * node) inline constexpr private
Recursively erases the specified element including its sub-tree.
Removes the node element and prunes its associated sub-tree. References and iterators to the erased elements are invalidated. Other references and iterators are not affected. The container's size is reduded by the number of elements removed, that is the node and all nodes in its sub-tree. If the erased node is the root, the tree is empty.
Parameters
node The pointer to the element to erase.
Definition at line 1557 of file tree.hpp.
   {
     while (internal_node_type *current = node) {
       if (current->last_child) {
         if (current->right_sibling) {
           current->last_child->right_sibling = current->right_sibling;
         }
         node = current->first_child;
       } else if (current->right_sibling) {
         node = current->right_sibling;
       } else {
         node = nullptr;
       }
       std::destroy_at(current);
       node_allocator.deallocate(current, 1);
       --node_count;
     }
   }
References fcarouge::tree< Type, AllocatorType >::internal_node_type::first_child, fcarouge::tree< Type, AllocatorType >::node_allocator, fcarouge::tree< Type, AllocatorType >::node_count, and fcarouge::tree< Type, AllocatorType >::internal_node_type::right_sibling.
Referenced by fcarouge::tree< Type, AllocatorType >::erase().
push() [1/2]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr iterator fcarouge::tree< Type, AllocatorType >::push (const_iterator position, const_reference value) inline constexpr
Inserts the given element value into the container directly after the last child of the position iterator as the new last child.
No iterators or references are invalidated. The new element is initialized as a copy of value. Type must meet the CopyInsertable requirement to use this overload. Inserts after the beginning begin() position as the last child of the root if present, or as the root if the container is empty. Inserts after the ending end() position as the sole child of the last node if present, or as the root if the container is empty.
Parameters
position The parent node constant iterator for which the element will be inserted as the last child. The iterator may be the beginning begin() or ending end() iterator.
value The data of the element to insert.
Returns
The iterator pointing to the inserted element.
Exceptions
Strong exception guarantees: no effect on exception. The Allocator::allocate() allocation or the element copy/move constructor/assignment may throw. If Type's move constructor is not noexcept and Type is not CopyInsertable into *this, the container will use the throwing move constructor. If it throws, the guarantee is waived and the effects are unspecified.
Note
This push modifier method definition is not represented in the Standard Template Library (STL) containers. The presence of the modifier is justified from the non-linear nature of the container in addition to the consistency claim with insert and emplace modifier method definitions.
Definition at line 1408 of file tree.hpp.
   {
     return { emplace_last_child(position.node, value) };
   }
References fcarouge::tree< Type, AllocatorType >::emplace_last_child(), and fcarouge::tree< Type, AllocatorType >::const_iterator::node.
push() [2/2]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr iterator fcarouge::tree< Type, AllocatorType >::push (const_iterator position, value_type && value) inline constexpr
Inserts the given element value into the container directly after the last child of the position iterator as the new last child.
No iterators or references are invalidated. The new element is initialized with a move of value. Type must meet the MoveInsertable requirement to use this overload. Inserts after the beginning begin() position as the last child of the root if present, or as the root if the container is empty. Inserts after the ending end() position as the sole child of the last node if present, or as the root if the container is empty.
Parameters
position The parent node constant iterator for which the element will be inserted as the last child. The iterator may be the beginning begin() or ending end() iterator.
value The data of the element to insert.
Returns
The iterator pointing to the inserted element.
Exceptions
Strong exception guarantees: no effect on exception. The Allocator::allocate() allocation or the element copy/move constructor/assignment may throw.
Note
This push modifier method definition is not represented in the Standard Template Library (STL) containers. The presence of the modifier is justified from the non-linear nature of the container in addition to the consistency claim with insert and emplace modifier method definitions.
Definition at line 1440 of file tree.hpp.
   {
     return { emplace_last_child(position.node, std::move(value)) };
   }
References fcarouge::tree< Type, AllocatorType >::emplace_last_child(), and fcarouge::tree< Type, AllocatorType >::const_iterator::node.
push_front() [1/2]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr void fcarouge::tree< Type, AllocatorType >::push_front (const_reference value) inline constexpr
Prepends the given element to the beginning of the container.
Prepends the given element as the new root. If the container is not empty the root becomes the sole child of the prepended element. No iterators or references are invalidated. The new element is initialized as a copy of value. Type must meet the CopyInsertable requirement to use this overload.
Parameters
value The data of the element to prepend.
Complexity
Constant.
Exceptions
Strong exception guarantees: no effect on exception. The Allocator::allocate() allocation or the element copy/move constructor/assignment may throw. If Type's move constructor is not noexcept and Type is not CopyInsertable into *this, the container will use the throwing move constructor. If it throws, the guarantee is waived and the effects are unspecified.
Definition at line 1464 of file tree.hpp.
   {
     emplace_root(value);
   }
References fcarouge::tree< Type, AllocatorType >::emplace_root().
push_front() [2/2]
template<class Type , class AllocatorType = std::allocator<Type>> constexpr void fcarouge::tree< Type, AllocatorType >::push_front (value_type && value) inline constexpr
Prepends the given element to the beginning of the container.
Prepends the given element as the new root. If the container is not empty the root becomes the sole child of the prepended element. No iterators or references are invalidated. The new element is initialized with a move of value. Type must meet the MoveInsertable requirement to use this overload.
Parameters
value The data of the element to prepend.
Complexity
Constant.
Exceptions
Strong exception guarantees: no effect on exception. The Allocator::allocate() allocation or the element copy/move constructor/assignment may throw.
Definition at line 1484 of file tree.hpp.
   {
     emplace_root(std::move(value));
   }
References fcarouge::tree< Type, AllocatorType >::emplace_root().
size()
template<class Type , class AllocatorType = std::allocator<Type>> constexpr size_type fcarouge::tree< Type, AllocatorType >::size () const inline constexpr noexcept
Returns the number of elements in the container.
The absolute distance between the beginning and end iterators.
Returns
The number of elements in the container.
Complexity
Constant.
Definition at line 990 of file tree.hpp.
   {
     return node_count;
   }
References fcarouge::tree< Type, AllocatorType >::node_count.
Referenced by operator==().
swap()
template<class Type , class AllocatorType = std::allocator<Type>> void fcarouge::tree< Type, AllocatorType >::swap (tree< Type, AllocatorType > & other)
Exchanges the contents of this container with those of the other container.
Does not invoke any move, copy, or swap operations on individual elements. All iterators and references remain valid. The Compare objects must be Swappable, and they are exchanged using unqualified call to non-member swap. If std:: allocator_traits<allocator_type>:: propagate_on_container_swap:: value is true, then the allocators are exchanged using an unqualified call to non-member swap. Otherwise, they are not swapped (and if get_allocator() != other.get_allocator(), the behavior is undefined).
Parameters
other The container to exchange the contents with.
Complexity
Constant.
Note
Iterators and references referring to an element in a container before the swap refers to the same element in the other container afterwards.
Member Data Documentation
node_allocator
template<class Type , class AllocatorType = std::allocator<Type>> internal_node_allocator_type fcarouge::tree< Type, AllocatorType >::node_allocator {} private
Definition at line 1793 of file tree.hpp.
Referenced by fcarouge::tree< Type, AllocatorType >::assign(), fcarouge::tree< Type, AllocatorType >::axe(), fcarouge::tree< Type, AllocatorType >::copy(), fcarouge::tree< Type, AllocatorType >::emplace(), fcarouge::tree< Type, AllocatorType >::emplace_front(), fcarouge::tree< Type, AllocatorType >::emplace_last_child(), fcarouge::tree< Type, AllocatorType >::emplace_root(), fcarouge::tree< Type, AllocatorType >::get_allocator(), fcarouge::tree< Type, AllocatorType >::insert(), fcarouge::tree< Type, AllocatorType >::max_size(), fcarouge::tree< Type, AllocatorType >::operator=(), and fcarouge::tree< Type, AllocatorType >::prune().
node_count
template<class Type , class AllocatorType = std::allocator<Type>> size_type fcarouge::tree< Type, AllocatorType >::node_count = 0 private
The number of elements in the container.
Definition at line 1799 of file tree.hpp.
Referenced by fcarouge::tree< Type, AllocatorType >::assign(), fcarouge::tree< Type, AllocatorType >::clear(), fcarouge::tree< Type, AllocatorType >::emplace(), fcarouge::tree< Type, AllocatorType >::emplace_front(), fcarouge::tree< Type, AllocatorType >::emplace_last_child(), fcarouge::tree< Type, AllocatorType >::emplace_root(), fcarouge::tree< Type, AllocatorType >::empty(), fcarouge::tree< Type, AllocatorType >::insert(), fcarouge::tree< Type, AllocatorType >::operator=(), fcarouge::tree< Type, AllocatorType >::prune(), and fcarouge::tree< Type, AllocatorType >::size().
root
template<class Type , class AllocatorType = std::allocator<Type>> internal_node_type* fcarouge::tree< Type, AllocatorType >::root = nullptr private
The root node of the container.
Definition at line 1796 of file tree.hpp.
Referenced by fcarouge::tree< Type, AllocatorType >::assign(), fcarouge::tree< Type, AllocatorType >::begin(), fcarouge::tree< Type, AllocatorType >::cbegin(), fcarouge::tree< Type, AllocatorType >::clear(), fcarouge::tree< Type, AllocatorType >::cleave(), fcarouge::tree< Type, AllocatorType >::emplace(), fcarouge::tree< Type, AllocatorType >::emplace_front(), fcarouge::tree< Type, AllocatorType >::emplace_last_child(), fcarouge::tree< Type, AllocatorType >::emplace_root(), fcarouge::tree< Type, AllocatorType >::front(), fcarouge::tree< Type, AllocatorType >::insert(), fcarouge::tree< Type, AllocatorType >::operator=(), fcarouge::tree< Type, AllocatorType >::tree(), and fcarouge::tree< Type, AllocatorType >::~tree().
The documentation for this class was generated from the following file:
include/fcarouge/tree.hpp