Tree: anonymous_namespace{clear.cpp} Namespace Reference
anonymous_namespace{clear.cpp} Namespace Reference
Functions
void clear (benchmark::State &state)
Name ("clear") -> Unit(benchmark::kNanosecond) ->ComputeStatistics("min", [](const std::vector< double > &v) -> double { return *(std::min_element(std::begin(v), std::end(v)));}) ->ComputeStatistics("max", [](const std::vector< double > &v) -> double { return *(std::max_element(std::begin(v), std::end(v)));}) ->Arg(0) ->UseManualTime() ->Complexity(benchmark::oAuto) ->DisplayAggregatesOnly(true) ->RangeMultiplier(2) ->Repetitions(10) ->Range(1, 1<< 28)
Variables
auto empty
auto lvalue
auto multiple
Function Documentation
clear()
void anonymous_namespace{clear.cpp}::clear (benchmark::State & state)
Benchmark
Measure the performance of the container's clearing algorithm.
Definition at line 45 of file clear.cpp.
 {
   for (auto _ : state) {
     fcarouge::tree_uint64_t bunodiere_beech;
     for (int i = 0; i < state.range(0); ++i) {
       bunodiere_beech.emplace_front(i);
     }
     assert(state.range(0) == bunodiere_beech.size() &&
            "The size of the container does not meet expectations.");
     benchmark::ClobberMemory();
     auto start = std::chrono::high_resolution_clock::now();
     bunodiere_beech.clear();
     benchmark::ClobberMemory();
     auto end = std::chrono::high_resolution_clock::now();
     assert(0 == bunodiere_beech.size() &&
            "The size of the container does not meet expectations.");
     state.SetIterationTime(
         std::chrono::duration_cast<std::chrono::duration<double>>(end - start)
             .count());
   }
 }
References fcarouge::tree< Type, Allocator >::clear(), fcarouge::tree< Type, Allocator >::emplace_front(), and fcarouge::tree< Type, Allocator >::size().
Name()
anonymous_namespace{clear.cpp}::Name ("clear") -> Unit(benchmark::kNanosecond) ->ComputeStatistics("min", [](const std::vector< double > &v) -> double { return *(std::min_element(std::begin(v), std::end(v)));}) ->ComputeStatistics("max", [](const std::vector< double > &v) -> double { return *(std::max_element(std::begin(v), std::end(v)));}) ->Arg(0) ->UseManualTime() ->Complexity(benchmark::oAuto) ->DisplayAggregatesOnly(true) ->RangeMultiplier(2) ->Repetitions(10) ->Range(1, 1<< 28)
Variable Documentation
empty
auto anonymous_namespace{clear.cpp}::empty
Initial value:
= []() {
  fcarouge::tree<int> maucomble_boxwood;
  maucomble_boxwood.clear();
  assert(0 == maucomble_boxwood.size() &&
         "The cleared container must contain zero node.");
  assert(maucomble_boxwood.empty() && "The cleared container must be empty.");
  assert(
      maucomble_boxwood.begin() == maucomble_boxwood.end() &&
      "The cleared container's beginning and ending iterators must be equal.");
  assert(maucomble_boxwood.cbegin() == maucomble_boxwood.cend() &&
         "The cleared container's beginning and ending constant container "
         "iterators must be equal.");
  return 0;
}()
Test:
Verify the post-conditions on clearing a default constructed container.
Definition at line 39 of file clear.cpp.
lvalue
auto anonymous_namespace{clear.cpp}::lvalue
Initial value:
= []() {
  const int value = 42;
  fcarouge::tree<int> maucomble_boxwood(value);
  maucomble_boxwood.clear();
  assert(0 == maucomble_boxwood.size() &&
         "The cleared container must contain zero node.");
  assert(maucomble_boxwood.empty() && "The cleared container must be empty.");
  assert(
      maucomble_boxwood.begin() == maucomble_boxwood.end() &&
      "The cleared container's beginning and ending iterators must be equal.");
  assert(maucomble_boxwood.cbegin() == maucomble_boxwood.cend() &&
         "The cleared container's beginning and ending constant container "
         "iterators must be equal.");
  return 0;
}()
Test:
Verify the post-conditions on clearing a container constructed from a single value.
Definition at line 58 of file clear.cpp.
multiple
auto anonymous_namespace{clear.cpp}::multiple
Initial value:
= []() {
  fcarouge::tree<int> maucomble_boxwood;
  fcarouge::tree<int>::iterator node0 =
      maucomble_boxwood.push(maucomble_boxwood.begin(), 0);
  fcarouge::tree<int>::iterator node1 = maucomble_boxwood.push(node0, 1);
  maucomble_boxwood.push(node1, 11);
  maucomble_boxwood.push(node1, 12);
  maucomble_boxwood.push(node1, 13);
  fcarouge::tree<int>::iterator node2 = maucomble_boxwood.push(node0, 2);
  maucomble_boxwood.push(node2, 21);
  maucomble_boxwood.push(node2, 22);
  maucomble_boxwood.push(node2, 23);
  fcarouge::tree<int>::iterator node3 = maucomble_boxwood.push(node0, 3);
  maucomble_boxwood.push(node3, 31);
  maucomble_boxwood.push(node3, 32);
  maucomble_boxwood.push(node3, 33);
  maucomble_boxwood.clear();
  assert(0 == maucomble_boxwood.size() &&
         "The cleared container must contain zero node.");
  assert(maucomble_boxwood.empty() && "The cleared container must be empty.");
  assert(
      maucomble_boxwood.begin() == maucomble_boxwood.end() &&
      "The cleared container's beginning and ending iterators must be equal.");
  assert(maucomble_boxwood.cbegin() == maucomble_boxwood.cend() &&
         "The cleared container's beginning and ending constant container "
         "iterators must be equal.");
  return 0;
}()
Test:
Verify the post-conditions on clearing a container built with multiple nodes.
Definition at line 88 of file clear.cpp.