name: Code Lint Verification

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt update
    - name: install
      run: sudo apt install clang-tidy-10 g++-10
    - name: tidy
      run: clang-tidy-10 include/fcarouge/tree.hpp --warnings-as-errors=* -- -std=c++2a
