name: Code Style Verification

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt update
    - name: install
      run: sudo apt install clang-format-10
    - name: format
      run: find . -iname *.hpp -o -iname *.cpp | xargs clang-format-10 --Werror --dry-run --verbose -style=file
