name: "Deploy Documentation: Doxygen GitHub Pages"

on:
  push:
    branches: [ develop ]

jobs:
  doxygen:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Doxygen
      uses: mattnotmitt/doxygen-action@v1.3.1
      with:
        working-directory: '.'
        doxyfile-path: 'doc/Doxyfile'
    - name: Deploy
      uses: peaceiris/actions-github-pages@v3.1.12
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/html
