name: Test Ubuntu 18.04 GCC 8

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt update
    - name: install
      run: sudo apt install gcc-8 g++-8
    - name: build
      run: gcc-8 test/*.cpp -Iinclude -Wall -Wextra -pedantic -std=c++2a
    - name: run
      run: ./a.out
