name: Test Ubuntu 20.04 GCC 10

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt update
    - name: install
      run: sudo apt install gcc-10 g++-10
    - name: build
      run: gcc-10 test/*.cpp -Iinclude -Wall -Wextra -pedantic -std=c++2a -lstdc++
    - name: run
      run: ./a.out
