name: "Test: Ubuntu 18.04 GCC 10"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  gcc:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: update
      run: sudo apt update
    - name: install
      run: sudo apt install gcc-10 g++-10
    - name: build
      run: gcc-10 sample/*.cpp test/*.cpp src/*.cpp -Iinclude -Wall -Wextra -pedantic -std=c++2a -lstdc++
    - name: run
      run: ./a.out
