name: "Test: Ubuntu 20.04 GCC 10"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  gcc:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Update
      run: sudo apt update
    - name: Install
      run: sudo apt install gcc-10 g++-10
    - name: Build
      run: gcc-10 sample/*.cpp test/*.cpp src/*.cpp -Iinclude -Wall -Wextra -pedantic -std=c++2a -lstdc++
    - name: Run
      run: ./a.out
