name: "Test Documentation: Doxygen"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  doxygen:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Doxygen
      uses: mattnotmitt/doxygen-action@v1.3.1
      with:
        working-directory: '.'
        doxyfile-path: 'doc/Doxyfile'
