name: "Test Thread: Sanitizer"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt update
    - name: install
      run: sudo apt install gcc-10 g++-10
    - name: build
      run: gcc-10 sample/*.cpp test/*.cpp src/*.cpp -Iinclude -std=c++20 -g -fsanitize=thread -lstdc++
    - name: test
      run: TSAN_OPTIONS=verbosity=2 ./a.out
